### DISCUSSION TITLE
How to solve the error `repository owner is missing`

### DISCUSSION THREAD

**Discussion by lepadatu** [suzuki-shunsuke/tfcmt#860] [Deprecated (Support Request)] [answered]
### Question

Can you please, specify a valid config file?  I have tried with GHE and it fails...

tfcmt -config  ../config/tfcmt.yml  plan -- terraform plan -no-color
ERRO[0000] repository owner is missing

### Example Code

```console
$ tfcmt -config  ../config/tfcmt.yml  plan -- terraform plan -no-color
ERRO[0000] repository owner is missing
```

Configuration

```yaml
ghe_base_url: https://redacted
ghe_graphql_endpoint: https://redacted/api/graphql

ci:
  owner:
  - type: envsubst
    value: cristian-lepadatu
  repo:
  - type: envsubst
    value: test-repo
terraform:
  plan:
    template: |
      ## Plan Result
      {{if .Result}}
      <pre><code>{{ .Result }}
      </pre></code>
      {{end}}
      <details><summary>Details (Click me)</summary>

      <pre><code>{{ .CombinedOutput }}
      </pre></code></details>
```

### Reference

*
https://suzuki-shunsuke.github.io/tfcmt/usage
