### ISSUE TITLE
Support using `<details>` tag for Warnings

### ISSUE THREAD

**Issue by guitarrapc** [suzuki-shunsuke/tfcmt#1330]
### Feature Overview

Support using `<details>` tag if warnings exists, which is like what `Change Result (Click Me)` do.

### Why is the feature needed?

When there are many warnings, comments can become too long for the Warning section. Each warning requires 9 lines, so if there are 10 warnings, that totals 90 lines.

As you know, the best practice is to fix all warnings. However, some [AWSProvider v5 resources](https://github.com/hashicorp/terraform-provider-aws/issues/25636) may have potential issues that could leave warnings until v6.

**Comment by suzuki-shunsuke** [comment]
You may be aware, you can use a details tag by setting comment templates in a configuration file.

https://suzuki-shunsuke.github.io/tfcmt/config

But I think it's useful if we can use a details tag easily by option (environment variable, command line, configuration).

e.g.

```yaml
terraform:
  plan:
    disable_label: false
    wrap_warning_with_details: true
    max_warning_lines: 10 # If the number of lines of warning exceeds this setting, the warning is wrapped with a details tag
```

I can't come up with good names instead of `max_warning_lines`.
