### ISSUE TITLE
"tfcmt failed" error="html/template:default:12:11: no such template \"error_message\"

### ISSUE THREAD

**Issue by sonatard** [suzuki-shunsuke/tfcmt#1490]
### tfcmt version

```console
$ tfcmt -v
v4.14.0
```

### Environment

* OS: GitHub Actions ubuntu-latest
* CPU Architecture: x86

### Overview

I set up the configuration referring to the example, but it resulted in an error.

https://suzuki-shunsuke.github.io/tfcmt/config#example-configuration

### How to reproduce

```
  tfcmt \
            -var target:${{ env.GOOGLE_CLOUD_PROJECT }} \
            -config .tfcmt.yaml \
            plan -patch -skip-no-changes \
            -- terraform plan -lock=false
```

```yaml
terraform:
  templates:
    changed_result: |
      {{if .ChangedResult}}
      <details><summary>Change Result (Click me)</summary>
      {{wrapCode .ChangedResult}}
      </details>
      {{end}}
    change_outside_terraform: |
      {{if .ChangeOutsideTerraform}}
      <details><summary>:warning: Note: Objects have changed outside of Terraform</summary>
      {{wrapCode .ChangeOutsideTerraform}}
      </details>
      {{end}}
    warning: |
      {{if .Warning}}
      ## :warning: Warnings :warning:
      {{wrapCode .Warning}}
      {{end}}
    error_message: |
      {{if .ErrorMessages}}
      ## :warning: Errors
      {{range .ErrorMessages}}
      * {{. -}}
      {{- end}}{{end}}
  plan:
    template: |
      aiueo
      {{template "plan_title" .}}

      {{if .Link}}[CI link]({{.Link}}){{end}}

      {{template "result" .}}
      {{template "updated_resources" .}}

      {{template "changed_result" .}}
      {{template "change_outside_terraform" .}}
      {{template "warning" .}}
      {{template "error_message" .}}
    when_destroy:
      template: |
        abcde
        {{template "plan_title" .}}

        {{if .Link}}[CI link]({{.Link}}){{end}}

        {{template "deletion_warning" .}}

        {{template "result" .}}
        {{template "updated_resources" .}}

        {{template "changed_result" .}}
        {{template "change_outside_terraform" .}}
        {{template "warning" .}}
        {{template "error_message" .}}
    when_no_changes:
      disable_label: true

```

### Debug output

```console
$ 
```

### Expected behaviour

no error

### Actual behaviour

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
time="2024-11-23T16:41:33Z" level=error msg="tfcmt failed" error="html/template:default:12:11: no such template \"error_message\""
Error: Process completed with exit code 1.

**Comment by suzuki-shunsuke** [comment]
Thank you for your report!

1. I could reproduce the issue.

tfcmt.yaml

```yaml
terraform:
  templates:
    error_message: |
      {{if .ErrorMessages}}
      ## :warning: Errors
      {{range .ErrorMessages}}
      * {{. -}}
      {{- end}}{{end}}
  plan:
    template: |
      {{template "error_message" .}}
```

```tf
resource "null_resource" "foo" {}
```

```sh
terraform init
```

```console
$ tfcmt plan -- terraform plan

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.foo will be created
  + resource "null_resource" "foo" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
ERRO[0001] tfcmt failed                                  error="html/template:default:1:11: no such template \"error_message\""
```

2. I found the document is wrong. I could resolve the issue by modifying the configuration file.

```yaml
templates:
  error_message: |
    {{if .ErrorMessages}}
    ## :warning: Errors
    {{range .ErrorMessages}}
    * {{. -}}
    {{- end}}{{end}}
terraform:
  plan:
    template: |
      {{template "error_message" .}}
```
