### ISSUE TITLE
add reusable templates configuration

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfcmt#50]
ex.

```yaml
templates:
  title: "## Plan Result ({{.Vars.target}})"
terraform:
  plan:
    template: |
      {{template "title" .}}
```

And provides builtin templates.
