### ISSUE TITLE
support to define CI platforms in the configuration file

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfcmt#57]
```yaml
cis:
- name: foo
  env:
  - check:
    owner:
    repo:
    pr:
    sha:
```

```yaml
cis:
- name: circleci
  env:
  - check:  CIRCLECI
    owner:
    repo:
    pr: '{{env "CIRCLE_PULL_REQUEST"}}'
    sha: '{{env "CIRCLE_SHA1"}}'
    build_url: '{{env "CIRCLE_BUILD_URL"}}'
```
