### ISSUE TITLE
Disable label per result type

### ISSUE THREAD

**Issue by dtan4** [suzuki-shunsuke/tfcmt#623]
## What

Introduce `disable_label: <bool>` configuration to each result type, in addition to global `terraform.plan.disable_label`

```yaml
terraform:
  plan:
    when_destroy:
      disable_label: true # <====
    when_no_changes:
      disable_label: true # <====
```

## Why

As described in [doc](https://suzuki-shunsuke.github.io/tfcmt/compared-with-tfnotify#breaking-change-update-pull-request-labels-by-default), tfcmt adds labels to Pull Request by default.
We can disable this behavior *completely* by adding `terraform.plan.disable_label: true`. However, in some cases, we want to disable only specific labels. For example, some of our Terraform workflow don't need labels for succeeded `terraform plan` (`add-or-update`, `destroy`, `no-changes`), but still need a label for failed `terraform plan` (`plan-error`).

I think this is not a common case, but previously our CI workflow worked as above with tfnotify (tfnotify adds labels only when they're specified explicitly in config file). It would be great if we can get the same behavior by tfcmt.
